### ISSUE TITLE
VulkanFFT v.s regular openGL based FFT implementation

### ISSUE THREAD

**Issue by shuwang1** [Lichtso/VulkanFFT#2]
Hello Lichtso,

Regarding your comment, 
`However, in most cases you probably want a different library, because Vulkan does not change much about the GPU computations, but is a lot more complex than other APIs.`

Do you mean your VulkanFFT may be slower than regular openGL based FFT? Though I haven't been able to compare your VulkanFFT with other openGL based FFT implementations yet, I am curious to understand the potential performance difference.

Thank you for the great work!

**Comment by Lichtso** [comment]
Yes, I suspect it to be slower. This project is relatively new and optimizations like warm / profile guided planning (aka. wisdom) are missing. Also the actual implementation might waste performance on memory bank collisions. Other than that, it should be on par as the algorithms are in the same complexity class: O(n log n).

But it would be cool to have a comparison / benchmark.

**Comment by shuwang1** [comment]
Thank you for the prompt and detailed response!

**Comment by Lichtso** [comment]
As some time has passed, a new Vulkan FFT library was implemented: https://github.com/DTolm/VkFFT
You might want to check that out, it is better optimized and also comes with benchmarks.
