### ISSUE TITLE
Successfully built for Android NDK by specifying path to glslangValidator

### ISSUE THREAD

**Issue by sevagh** [Lichtso/VulkanFFT#3]
Hello,

I was successfully able to build this project for the Android NDK 20.1 with the following cmake invocation:

```
$ export NDK_DIR=$HOME/Android/Sdk/ndk/20.1.5948944
mkdir -p build && cd build && cmake .. \
              -DCMAKE_TOOLCHAIN_FILE=$NDK_DIR/build/cmake/android.toolchain.cmake \
              -DVulkan_LIBRARY=$NDK_DIR/platforms/android-24/arch-arm64/usr/lib/libvulkan.so
              -DVulkan_INCLUDE_DIR=$NDK_DIR/sysroot/usr/include \
              -DANDROID_PLATFORM=24 \
              -DANDROID_ABI=arm64-v8a
```

The only special thing I had to do was replace `${VULKAN_SDK}/bin/glslangValidator` with `$HOME/Android/Sdk/emulator/lib64/vulkan/glslangValidator` in CMakeLists.txt.

Is this any use as an upstream contribution? Perhaps make a `GLSLANG_VALIDATOR_PATH` configurable or something of that nature.

**Comment by Lichtso** [comment]
Thanks, I changed it.
However, travis CI builds are still unstable.
I will try to get it to run in the coming days.

**Comment by sevagh** [comment]
Thanks!
